server:
  port: 8080
spring:
  application:
    name: FirstSpringApp
  datasource:
    url: jdbc:mysql://localhost:3306/productmanagementsystem
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: Samir
    password: Samir242004

